export const portalTools = [
  { name: 'geojson.io', category: '在线编辑', url: 'https://geojson.io/', tags: ['GeoJSON', '绘制', '编辑'], description: '在线绘制、检查和快速分享 GeoJSON。' },
  { name: 'mapshaper', category: '格式转换', url: 'https://mapshaper.org/', tags: ['Shapefile', 'GeoJSON', '简化'], description: '在线矢量格式转换、简化、字段处理。' },
  { name: 'Overpass Turbo', category: '数据下载', url: 'https://overpass-turbo.eu/', tags: ['OSM', 'Overpass', '查询'], description: '可视化编写和调试 OSM Overpass 查询。' },
  { name: 'Geofabrik Downloads', category: '数据下载', url: 'https://download.geofabrik.de/', tags: ['OSM', 'PBF', 'Shapefile'], description: '按国家和地区下载 OSM 离线数据。' },
  { name: 'BBBike Extracts', category: '数据下载', url: 'https://extract.bbbike.org/', tags: ['OSM', '裁剪', '多格式'], description: '自定义范围下载 OSM 多格式数据。' },
  { name: 'OpenStreetMap Wiki', category: '数据下载', url: 'https://wiki.openstreetmap.org/', tags: ['OSM', '标签', '文档'], description: '查询 OSM 标签体系、数据模型和工具说明。' },
  { name: 'EPSG.io', category: '坐标工具', url: 'https://epsg.io/', tags: ['EPSG', '投影', '坐标系'], description: '搜索 EPSG 坐标系、WKT、Proj4 和转换参数。' },
  { name: 'MapTiler Coordinates', category: '坐标工具', url: 'https://epsg.io/map', tags: ['坐标拾取', 'EPSG'], description: '在线拾取坐标并辅助检查坐标系统。' },
  { name: 'MyGeodata Converter', category: '格式转换', url: 'https://mygeodata.cloud/converter/', tags: ['格式转换', 'CAD', 'GIS'], description: '在线转换常见 GIS/CAD 格式。' },
  { name: 'GDAL Vector Drivers', category: '开发文档', url: 'https://gdal.org/drivers/vector/index.html', tags: ['GDAL', 'OGR', '格式'], description: '官方矢量格式支持清单和驱动参数。' },
  { name: 'Turf.js Docs', category: '开发文档', url: 'https://turfjs.org/docs/', tags: ['空间分析', 'JavaScript'], description: '浏览器端空间分析函数官方文档。' },
  { name: 'deck.gl Docs', category: '可视化', url: 'https://deck.gl/docs', tags: ['WebGL', 'HeatmapLayer', 'ArcLayer'], description: 'WebGL 地理可视化图层和 Mapbox 集成文档。' },
  { name: 'AntV L7 Docs', category: '可视化', url: 'https://l7.antv.antgroup.com/', tags: ['WebGL', '热力', '飞线'], description: '蚂蚁 L7 地理可视化图层和场景文档。' },
  { name: 'Mapbox GL JS Docs', category: '开发文档', url: 'https://docs.mapbox.com/mapbox-gl-js/', tags: ['Mapbox', 'Style', 'Layer'], description: 'Mapbox GL JS 样式、图层和交互官方文档。' },
  { name: '高德开放平台 Web服务', category: '数据下载', url: 'https://lbs.amap.com/api/webservice/summary/', tags: ['高德', 'POI', 'Web Service'], description: '高德 POI、地理编码、路径规划等 Web 服务文档。' },
  { name: 'Placemark Play', category: '在线编辑', url: 'https://play.placemark.io/', tags: ['GeoJSON', '编辑', '知乎整理'], description: '在线创建、编辑、分析和导出地图数据。' },
  { name: 'Vector | GeoJSON Editor', category: '在线编辑', url: 'https://vector.rocks/', tags: ['GeoJSON', '矢量编辑', '知乎整理'], description: '面向 GIS 数据的轻量 GeoJSON 创建、编辑和处理工具。' },
  { name: 'Geoman GeoJSON Demo', category: '在线编辑', url: 'https://www.geoman.io/demo', tags: ['GeoJSON', '绘制', '知乎整理'], description: '基于 Geoman 的在线要素绘制和 GeoJSON 编辑示例。' },
  { name: 'L7Editor', category: '在线编辑', url: 'https://l7editor.antv.antgroup.com/', tags: ['绘制', 'L7', 'DipperMap'], description: '蚂蚁 L7 多底图地理绘制和数据编辑工具。' },
  { name: 'Maptable', category: '在线编辑', url: 'https://maptable.com/zh-cn/', tags: ['协同', '空间数据', 'DipperMap'], description: '在线空间数据协同、编辑和地图分享工具。' },
  { name: 'Scribble Maps', category: '在线编辑', url: 'https://www.scribblemaps.com/', tags: ['绘制', '在线地图', 'DipperMap'], description: '在线绘制自定义地图、形状和标注。' },
  { name: 'tool.lu 坐标转换', category: '坐标工具', url: 'https://tool.lu/coordinate/', tags: ['WGS84', 'GCJ02', 'BD09'], description: '在线进行国内常见地图坐标系互转，并提供坐标拾取入口。' },
  { name: 'LDDGO 坐标转换', category: '坐标工具', url: 'https://www.lddgo.net/base/class?classID=8', tags: ['坐标转换', '经纬度', 'DipperMap'], description: '坐标、经纬度查询和常用坐标转换工具集合。' },
  { name: '武大吉奥坐标系转换', category: '坐标工具', url: 'http://www.wmksj.com/tool/coordinate.html', tags: ['WGS84', 'GCJ02', 'BD09'], description: 'BD09、GCJ02、WGS84 坐标系互转工具。' },
  { name: '高德坐标拾取器', category: '坐标工具', url: 'https://lbs.amap.com/tools/picker', tags: ['高德', '坐标拾取', 'GCJ02'], description: '高德开放平台提供的地图坐标拾取工具。' },
  { name: '百度地图坐标拾取器', category: '坐标工具', url: 'https://api.map.baidu.com/lbsapi/getpoint/', tags: ['百度', '坐标拾取', 'BD09'], description: '百度地图开放平台提供的坐标拾取工具。' },
  { name: '腾讯位置服务坐标拾取器', category: '坐标工具', url: 'https://lbs.qq.com/getPoint/', tags: ['腾讯', '坐标拾取', 'GCJ02'], description: '腾讯位置服务提供的地图坐标拾取工具。' },
  { name: 'Gdal3.js', category: '格式转换', url: 'https://gdal3.js.org/', tags: ['GDAL', '浏览器', 'DipperMap'], description: '在浏览器中进行栅格、矢量格式转换和坐标转换。' },
  { name: 'DataV.GeoAtlas', category: '数据资源', url: 'https://datav.aliyun.com/portal/school/atlas/area_selector', tags: ['行政区', 'GeoJSON', 'DipperMap'], description: '阿里云 DataV 行政区边界数据下载和层级选择工具。' },
  { name: 'L7 地理小工具', category: '数据资源', url: 'https://l7.antv.antgroup.com/custom/tools', tags: ['行政区', '地理编码', 'DipperMap'], description: 'AntV L7 提供的行政区划、地理编码等地理小工具。' },
  { name: '省市县数据 CTAmap', category: '数据资源', url: 'https://www.shengshixian.com/', tags: ['行政区划', '矢量数据', '省市县'], description: '长期序列中国行政区划矢量数据下载入口。' },
  { name: '标准地图服务', category: '数据资源', url: 'http://bzdt.ch.mnr.gov.cn/', tags: ['标准地图', '自然资源部', 'DipperMap'], description: '自然资源部标准地图服务入口。' },
  { name: '民政部中国地图', category: '数据资源', url: 'http://xzqh.mca.gov.cn/map', tags: ['行政区划', '民政部', 'DipperMap'], description: '民政部全国行政区划地图查询入口。' },
  { name: '天地图', category: '在线地图', url: 'https://www.tianditu.gov.cn/', tags: ['底图', '国家平台', 'DipperMap'], description: '国家地理信息公共服务平台在线地图。' },
  { name: '百度地图', category: '在线地图', url: 'https://map.baidu.com/', tags: ['在线地图', 'BD09', 'DipperMap'], description: '百度在线地图和地点查询入口。' },
  { name: '高德地图', category: '在线地图', url: 'https://www.amap.com/', tags: ['在线地图', 'GCJ02', 'DipperMap'], description: '高德在线地图、路线和 POI 查询入口。' },
  { name: '腾讯地图', category: '在线地图', url: 'https://map.qq.com/', tags: ['在线地图', 'GCJ02', 'DipperMap'], description: '腾讯在线地图、地点和路线查询入口。' },
  { name: 'HERE Maps', category: '在线地图', url: 'https://maps.here.com/', tags: ['在线地图', '海外', 'DipperMap'], description: 'HERE 提供的全球在线地图服务。' },
  { name: 'Google Maps', category: '在线地图', url: 'https://www.google.com/maps', tags: ['在线地图', '海外', 'DipperMap'], description: 'Google 全球在线地图和地点查询入口。' },
  { name: 'QGIS', category: 'GIS软件', url: 'https://www.qgis.org/', tags: ['桌面 GIS', '开源', 'DipperMap'], description: '开源桌面 GIS 软件，支持空间数据查看、编辑和分析。' },
  { name: 'GeoDa', category: 'GIS软件', url: 'https://geodacenter.github.io/index-cn.html', tags: ['空间统计', '空间分析', 'DipperMap'], description: '面向空间分析和空间统计研究的开源软件。' },
  { name: 'TileMill', category: 'GIS软件', url: 'https://tilemill-project.github.io/tilemill/', tags: ['地图设计', '制图', 'DipperMap'], description: '开源地图设计工作室和制图工具。' },
  { name: 'uDig', category: 'GIS软件', url: 'http://udig.refractions.net/', tags: ['桌面 GIS', '开源', 'DipperMap'], description: '轻量级桌面 GIS，可连接多种数据源并进行地图编辑。' },
  { name: 'L7VP', category: '可视化', url: 'https://li.antv.antgroup.com', tags: ['在线制图', '可视分析', 'DipperMap'], description: '蚂蚁地理空间智能可视分析和地图应用搭建平台。' },
  { name: 'kepler.gl', category: '可视化', url: 'https://kepler.gl/', tags: ['大数据', 'WebGL', 'DipperMap'], description: '开源大规模地理空间数据可视化分析工具。' },
  { name: 'Foursquare Studio', category: '可视化', url: 'https://studio.foursquare.com/home', tags: ['位置数据', '分析', 'DipperMap'], description: '位置数据可视化、空间分析和地图表达工具。' },
  { name: 'ColorBrewer', category: '可视化', url: 'https://colorbrewer2.org/', tags: ['地图配色', '制图', 'DipperMap'], description: '经典地图分级设色和配色方案选择工具。' },
  { name: 'Felt', category: '可视化', url: 'https://felt.com', tags: ['在线制图', '分享', 'DipperMap'], description: '快速创建、协作和分享交互式地图。' },
  { name: 'Mapbox Developer Tools', category: '开发文档', url: 'https://docs.mapbox.com/resources/dev-tools/', tags: ['Mapbox', '开发工具', 'DipperMap'], description: 'Mapbox 服务和 API 相关开发工具集合。' },
  { name: 'Google Earth Engine', category: '遥感平台', url: 'https://earthengine.google.com/', tags: ['遥感', '云计算', 'DipperMap'], description: 'Google 提供的云端地球观测数据处理和分析平台。' },
  { name: 'AIEarth', category: '遥感平台', url: 'https://engine-aiearth.aliyun.com/#/', tags: ['遥感', '阿里云', 'DipperMap'], description: '阿里云地球引擎，支持地理信息处理和可视化服务。' },
  { name: '星球地图', category: '遥感平台', url: 'https://online.geovisearth.com/browser', tags: ['遥感', 'GeoVis', 'DipperMap'], description: 'GeoVis Earth 在线浏览器和地理可视化服务。' },
  { name: 'SenseEarth Cloud', category: '遥感平台', url: 'https://senseearth-cloud.com/', tags: ['地球观测', '遥感分析', 'DipperMap'], description: '地球观测数据处理、分析和云服务平台。' },
  { name: 'PIESAT Engine', category: '遥感平台', url: 'https://engine.piesat.cn/', tags: ['卫星影像', '遥感应用', 'DipperMap'], description: '航天宏图提供的全球卫星影像数据服务与应用平台。' },
  { name: 'EO Browser', category: '遥感平台', url: 'https://apps.sentinel-hub.com/eo-browser', tags: ['Sentinel', '遥感浏览', 'DipperMap'], description: 'Sentinel Hub 提供的在线遥感影像浏览工具。' },
  { name: 'EOS LandViewer', category: '遥感平台', url: 'https://eos.com/landviewer/?day=true&s=Modis', tags: ['卫星影像', '遥感浏览', 'DipperMap'], description: '在线卫星影像检索、浏览和地理信息平台。' },
  { name: '卫星资源中心数据平台', category: '遥感平台', url: 'https://data.cresda.cn/#/home', tags: ['卫星数据', 'CRESDA', 'DipperMap'], description: '中国资源卫星应用中心卫星数据服务平台。' },
  { name: 'Awesome ArcGIS', category: '工具合集', url: 'https://github.com/esri-es/awesome-arcgis/', tags: ['ArcGIS', '资源合集', 'DipperMap'], description: 'ArcGIS 用户和开发人员相关资源集合。' },
  { name: 'Awesome ArcGIS Developers', category: '工具合集', url: 'https://github.com/Esri/awesome-arcgis-developers', tags: ['ArcGIS', '开发', 'DipperMap'], description: 'ArcGIS 开发资源、示例和工具精选列表。' },
  { name: 'Awesome Earth Observation Code', category: '工具合集', url: 'https://github.com/acgeospatial/awesome-earthobservation-code', tags: ['地球观测', '代码', 'DipperMap'], description: '地球观测和地理空间工具、教程、代码资源集合。' },
  { name: 'Awesome GEE', category: '工具合集', url: 'https://github.com/giswqs/Awesome-GEE', tags: ['GEE', '遥感', 'DipperMap'], description: 'Google Earth Engine 资源精选列表。' },
  { name: 'Awesome GeoJSON', category: '工具合集', url: 'https://github.com/tmcw/awesome-geojson', tags: ['GeoJSON', '工具合集', 'DipperMap'], description: 'GeoJSON 相关实用工具、库和资源列表。' },
  { name: 'Awesome Geospatial', category: '工具合集', url: 'https://github.com/sacridini/Awesome-Geospatial', tags: ['地理空间', '工具合集', 'DipperMap'], description: '地理空间工具、资源和项目精选集合。' },
  { name: 'Awesome Geospatial Companies', category: '工具合集', url: 'https://github.com/chrieke/awesome-geospatial-companies', tags: ['公司', '行业资源', 'DipperMap'], description: '全球地理空间、遥感、无人机和卫星行业公司列表。' },
  { name: 'Awesome Open Geoscience', category: '工具合集', url: 'https://github.com/softwareunderground/awesome-open-geoscience', tags: ['地球科学', '开源', 'DipperMap'], description: '开放地球科学相关工具、数据和资源集合。' },
  { name: 'Awesome QGIS', category: '工具合集', url: 'https://github.com/totpero/awesome-qgis', tags: ['QGIS', '插件', 'DipperMap'], description: 'QGIS 框架、库、插件、教程和文章资源精选列表。' },
  { name: 'Awesome Remote Sensing Change Detection', category: '工具合集', url: 'https://github.com/wenhwu/awesome-remote-sensing-change-detection', tags: ['遥感变化检测', '数据集', 'DipperMap'], description: '遥感变化检测相关数据集、代码、研究人员和竞赛列表。' },
  { name: 'Awesome Satellite Imagery Datasets', category: '工具合集', url: 'https://github.com/chrieke/awesome-satellite-imagery-datasets', tags: ['卫星影像', '数据集', 'DipperMap'], description: '带计算机视觉和深度学习标注的卫星影像数据集列表。' },
  { name: 'Awesome Vector Tiles', category: '工具合集', url: 'https://github.com/mapbox/awesome-vector-tiles', tags: ['矢量瓦片', 'Mapbox', 'DipperMap'], description: '实现 Mapbox Vector Tile 规范的工具和资源集合。' },
  { name: 'Awesome Historical Maps', category: '工具合集', url: 'https://github.com/stark1tty/Awesome-Historic_al-Maps', tags: ['历史地图', '数据资源', 'DipperMap'], description: '历史地图相关资源、数据库和工具精选列表。' },
  { name: 'Awesome 3D Tiles', category: '工具合集', url: 'https://github.com/pka/awesome-3d-tiles', tags: ['3D Tiles', '三维', 'DipperMap'], description: '3D Tiles 开放标准相关工具和资源集合。' },
  { name: 'GeoRust', category: '工具合集', url: 'https://georust.org/', tags: ['Rust', '地理空间', 'DipperMap'], description: 'Rust 语言地理空间工具和库社区入口。' }
]

export const portalCategories = ['全部', ...Array.from(new Set(portalTools.map((tool) => tool.category)))]
